name: Terraform Drift Detection

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.6
  TF_DIR: ./terra

jobs:
  drift:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]

    concurrency:
      group: terraform-drift-${{ matrix.env }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PYFLEET_ARN }}-${{ matrix.env }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -input=false -reconfigure
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan (Drift Detection)
        id: plan
        env:
          TF_VAR_env: ${{ matrix.env }}
          TF_VAR_active_color: "blue"
          TF_VAR_duckdns_token: ${{ secrets.DUCKDNS_TOKEN }}
          TF_VAR_duckdns_domain: ${{ secrets.DUCKDNS_DOMAIN }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
          TF_VAR_key: ${{ secrets.KEY }}
          TF_VAR_my_email: ${{ secrets.MY_EMAIL }}
          TF_VAR_my_ip_cidr: ${{ secrets.MY_IP_CIDR }}
#          TF_VAR_alert_emails: "[\"${{ secrets.ALERT_EMAILS }}\"]"
          TF_VAR_budget_amount: ${{ secrets.BUDGET_AMOUNT }}
          TF_VAR_bastion_ami: ${{ secrets.BASTION_AMI }}
          TF_VAR_app_ami: ${{ secrets.APP_AMI }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_us_east_1_cert_arn: ${{ secrets.US_EAST_1_CERT_ARN }}
        run: |
          set +e
          terraform plan \
            -detailed-exitcode \
            -input=false \
            -lock=false \
            -refresh=true
            -var='alert_emails=${{ secrets.ALERT_EMAILS }}'
          EXIT_CODE=$?
          set -e
          echo "EXIT_CODE=$EXIT_CODE" >> "$GITHUB_ENV"
        working-directory: ${{ env.TF_DIR }}

      - name: Check for Drift
        if: env.EXIT_CODE == '2'
        run: echo "Terraform drift detected for ${{ matrix.env }} environment!"

      - name: Create GitHub Issue if Drift Detected
        if: env.EXIT_CODE == '2'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Terraform Drift Detected - ${{ matrix.env }}"
          content-filepath: .github/drift-template.md
          labels: drift, terraform
